# whitelist
branches:
  only:
    - master
    - stable
language: java

jdk:
  - oraclejdk8

before_install:
  - mvn clean install -Dgpg.skip=true

before_install:
  - mvn clean install -Dgpg.skip=true

script:
  - mvn verify -Dgpg.skip=true

after_success:
  - chmod a+x deploy.sh
  - ./deploy.sh

after_failure:
  - cat com.github.lafa.logfast/target/surefire-reports/*.txt
  - cat com.github.lafa.logfast/core/target/surefire-reports/*.txt
