branches:
  only:
  - master
  - stable
language: java
jdk:
- oraclejdk8
before_install:
- echo $super_secret_password | gpg super_secret.txt.gpg
install:
- mvn clean install -Dgpg.skip=true
before_script: 
script: 
after_success:
- mvn clean deploy  -Dgpg.skip=true
after_failure:
- cat com.github.lafa.logfast/target/surefire-reports/*.txt
- cat com.github.lafa.logfast/core/target/surefire-reports/*.txt
env:
  global:
  - secure: X6Hb5ppxESjekDypMPZP670poKF3x7AjJ10XzZyIFOoyHPwRmVEOnb2knctMN3NcAmbJUoaX7ah+2ihKMPrhchfGHHNwq9a4RjFyfTYvXe8F7+bluYZFik00U7EJVkK2ssaSYJ0PsVqdeKvWoWjk+czmqFYhqhpsFCUVaOtGy2ZuBgOOTPPYMo34r+LCJhKdDtDJVBHH8/L9e2n3mqyWd8E+gvozOLf/XQ/L1hXI3cd4L/hIV5gf6qRhvMK+3XWah4KkZd+t+ON9PfBvoeOgXQlXrXxKyS1aLDWW5OORQClmZ2gsqLIGNnRUJDL95aKBdbURKDftrOo+dQbQJ0B1fIu/1i+7koD5Vpm0bFTNHyS/XVDKhRBJ8NRZbpcztO/VUmPzi4wkHbu7zCp4qsWTV/yR692KlzqqeV5JzJrzKaKO199K8SSTv2s16/fIBLNzzSj2b5wPgkm3H/wm6STfJvP8etUmasHhJUC9+VCjVcCVNTMZgxpRbYEd0iUMMXLAXvQ8lrQ6OOqqAb0R3fSVzOXaDrt459xdlmE/8AhXb0PtEY2Ugn5S887haR4D943+zPN0BvzKt9G8twObiXOSc3jSy/lBqE4B+s9TQZQLgLnwHSPn08i/QcSVnyL6l5eqArT57x0PhuglkgVe8C/QZPT0nEswuVmeHLhIg1PRN4o=
  - secure: NikoepN+9+vCrrB52VCPMEGAwGvi6NyR8qJua0BD9u5ipZULwJpOQJa0bNWAvylOHjlJOdKReLHioWsHl8LPo8HenNP/rhMFPWQU4A2zxzSh4IiXkXkJgjUc0irhIGlAT2xp7TBB0L9HwIj7Yk6DW9B9t0nhYl1p0Dx3at+fjmNPqy3ZF9kDH5UfNtbRz1kRbuPvWzdNodhEubOB1MvrcW2v5b23QxzGwN8vMWR5Tk7BlteHkfmmASg053KWRjgx3Cun9p3HgaW6nbIvUqz2s9RYYV2B95iqwDQC9Gfm6nhrlQ0Qh8RMtonq3HM0cIK4MkfkgaiLMUeYXkFrLofhi3+PV+8+HGcKEcfrUAQX1vYu1xuPvAPrc4c6T1tqzs1odMSbNb6HKFwW/ozMr88qd7re4ECdJ9i8y+qwI6Un2oXnOOf83PcVBQS+eFqajU1M2H4M2SQFs2dvrVG2DbXmC6lKF6cKo1GZyNorPpUlCS0zMUAHh8VuYVcs1IwyrdJmWc5Ys71AgnY0exW85LcEjP9oZ5yX55Yx3H655dIU6LKpb4u2aDBgsS6B2OK5pdh4ByOoFC7tFpplPqj9z4x16DYXjdZ5yTNgSfBXJbA07N/g5N4RIr/ojFxBPCgRry35A0H9HLalr4cDg0LtaJ/2aCcazcadCWDMgBXtf+IEe1s=
